version: "3"

services:

  loofah-database:
    image: mongo:latest
    ports:
    - 27017:27017

  loofah-front-end:
    build:
      context: ../../loofah-frontend
      dockerfile: ./Dockerfile
    environment:
    - REACT_APP_LOOFAH_API_URL=http://localhost:8080
    ports:
    - 3000:3000


